Prevents a possible "NPE", found in trunk demo logs (it's a treasure I will continue to dig in...)
freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
==> lastContent.description  [in template "component://ecommerce/webapp/ecommerce/content/viewcontent.ftl" at line 38, column 38]



git-svn-id: https://svn.apache.org/repos/asf/ofbiz/trunk/specialpurpose@1721067 13f79535-47bb-0310-9956-ffa450edef68