Fixed: Error running the simple-method: Error running groovy script (OFBIZ-9432)
Steps to reproduce the error:
Add producs to cart (i.e. 2 x RoundGizmo) 
-> [Quick Checkout] 
-> Checkout Without Login: Quick Checkout 
-> Basic Information: fill in required fields 
-> Continue 

Error: unable to resolve class CartItemModifyException

jleroux: Groovy needs the complete path to CartItemModifyException
Found the same in CustomerEvents.xml

Thanks: Daniel Coric for report

git-svn-id: https://svn.apache.org/repos/asf/ofbiz/ofbiz-plugins/trunk@1799860 13f79535-47bb-0310-9956-ffa450edef68